[project]
name = "lebesgue-integration-analysis"
version = "1.0.0"
description = "Lebesgue Integration Analysis"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
]
